# SPDX-License-Identifier: Apache-2.0
# Disabled after repeat system_server crashes in native capture-only tests.
# Keep the original upper-mic repair; do not enable until crash isolation passes.
RELAY_ENABLED=0
